---
title: "CodeBooK"
author: "Mónica Arellano y Dulce Rodríguez"
date: "8 de junio de 2017"
output: html_document
---

#Benemérita Universidad Autonoma de Puebla
##Facultad de ciencias Físico Matemáticas
##Licenciatura de Actuaría
###Programación Actuarial III

###Caso RAH con celulares (descripción de la base de datos)

Los experimentos se llevaron a cabo con un grupo de 30 voluntarios dentro de un margen de edad de 19 a 48 años. Cada persona realizo seis actividades (caminar, caminar escaleras arriba, caminar escaleras abajo,estar sentado, estar parado y estar acostado) todas ellas mientras utilizaban un teléfono Samsung Galaxy SII en la cintura. Utilizando el acelerómetro y el giroscopio incorporados , se capto la aceleracion lineal 3-axial y la velocidad angular 3-axial a una velocidad constante de 50 Hz.  Los experimentos se grabaron en vídeo para etiquetar los datos de forma manual. El conjunto de datos obtenidos se  dividio aleatoriamente en dos grupos, en lel que se seleccionó el 70% de los voluntarios para la generación de los datos de entrenamiento y 30%  para los datos de prueba.

Las señales del sensor (acelerómetro y giroscopio) fueron pre-procesados mediante la aplicación de filtros de ruido y luego se muestrean en deslizamiento de ancho fijo ventanas de 2,56 seg y 50% de solapamiento. La señal de aceleración del sensor, que tiene componentes gravitacionales y el movimiento del cuerpo, se separó usando un filtro de paso bajo Butterworth en aceleración cuerpo y la gravedad.Se supone que la fuerza gravitacional sólo tiene componentes de baja frecuencia, por lo que se utilizó un filtro con una frecuencia de corte de 0,3 Hz. A partir de cada ventana, se obtuvo un vector de características calculando variables a partir del dominio de tiempo y frecuencia. 


####Datos originales

Se proporciona:

- Un vector de 561 características con variables de dominio de tiempo y frecuencia.
- Su etiqueta de actividad.
- Un identificador del sujeto que realizó el experimento.

Las señales fueron utilizadas para estimar variables del vector para cada patrón: 'XYZ' es utilizado para denotar señales de 3 ejes en direcciones X, Y y Z.

En un listado tenemos las características:
tBodyAcc-XYZ
tGravityAcc-XYZ
tBodyAccJerk-XYZ
tBodyGyro-XYZ
tBodyGyroJerk-XYZ
tBodyAccMag
tGravityAccMag
tBodyAccJerkMag
tBodyGyroMag
tBodyGyroJerkMag
fBodyAcc-XYZ
fBodyAccJerk-XYZ
fBodyGyro-XYZ
fBodyAccMag
fBodyAccJerkMag
fBodyGyroMag
fBodyGyroJerkMag


El conjunto de variables que se estimaron a partir de estas señales son:

Mean (): Promedio.
Std (): Desviación estándar.
Mad (): Desviación absoluta media.
Max (): El valor más grande en matrizuna. 
Min (): El valor más pequeño en matriz.
Sma (): Area de magnitud de  señal.
Energy (): Medida de energía. Suma de los cuadrado divididos por el número de valores.
Iqr (): Intervalo intercuartílico.
Entropy (): Entropía de señal.
ArCoeff (): Coeficientes de autorregresión con orden Burg igual a 4.
Correlation (): Coeficiente de correlación entre dos señales.
MaxInds (): Índice de la componente de frecuencia con mayor magnitud.
MeanFreq (): Promedio ponderado de los componentes de frecuencia para obtener una frecuencia media.
Skewness (): Asimetría de la señal del dominio de frecuencia.
Kurtosis (): Kurtosis de la señal del dominio de la frecuencia.
BandsEnergy (): Energía de un intervalo de frecuencia dentro de los 64 contenedores de la FFT de cada ventana.
Angle (): Ángulo entre los vectores.


Vectores adicionales obtenidos promediando las señales en una muestra de ventana de señal. Estos se utilizan en la variable angle():

gravityMean
tBodyAccMean
tBodyAccJerkMean
tBodyGyroMean
tBodyGyroJerkMean


####Transformaciones

Las transfromaciones que se hiceron son:
-Unir los datos de test con los de training, para crear un solo conjunto de datos.
-extraer unicamente las medidads de media y desviacion estandar de cada medición.
-Colocar etiquetas apropiadas en la base de datos con nombres que las describan.
-Crear una segunda base de datos independiente con el promedio de cada variable para cada actividad y cada voluntario.
